apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: main
spec:
  strategy:
    canary:
      steps: []
  template:
    spec:
      containers:
        - name: kiyos
          livenessProbe: null

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: main
spec:
  maxUnavailable: 50%

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: main
spec:
  minReplicas: 1
  maxReplicase: 2
